# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('thumbsUp', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('views', models.IntegerField(default=0)),
                ('product_slug', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=30)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Category')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reviews.Product'),
        ),
    ]
