# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.IntegerField(blank=True, default=1511222615.3488338),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.FloatField(blank=True, default=1511222615.3488338, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reviews.Product'),
        ),
    ]
