# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20171112_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='thumbsUp',
            new_name='backs',
        ),
        migrations.AddField(
            model_name='product',
            name='thumbsDown',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbsUp',
            field=models.IntegerField(default=0),
        ),
    ]
