# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20171121_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='joined',
            field=models.IntegerField(blank=True, default=1512746928.267358),
        ),
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.IntegerField(blank=True, default=1512746928.2643535),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.FloatField(blank=True, default=1512746928.2618496, null=True),
        ),
    ]
