# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20171211_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.IntegerField(blank=True, default=1512951001.4642928),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.IntegerField(blank=True, default=1512951001.473807),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.FloatField(blank=True, default=1512951001.4557805, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='joined',
            field=models.IntegerField(blank=True, default=1512951001.468799),
        ),
    ]
