# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20171112_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
