# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20171112_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_slug',
            new_name='slug',
        ),
    ]
