# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20171112_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categorysaver',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
