# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20171211_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.IntegerField(blank=True, default=1512959361.5025513),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.IntegerField(blank=True, default=1512959361.521189),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.FloatField(blank=True, default=1512959361.5025513, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='joined',
            field=models.IntegerField(blank=True, default=1512959361.5196865),
        ),
    ]
