# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20171115_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_product_slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
