# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_comment_comment_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_product_slug',
        ),
    ]
