# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_comment_comment_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='added',
            field=models.IntegerField(blank=True, default=1510829809.404776),
        ),
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.IntegerField(blank=True, default=1510829809.404776),
        ),
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateField(auto_now=True),
        ),
    ]
