# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_auto_20171116_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.IntegerField(blank=True, default=1510868344.6110823),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.IntegerField(blank=True, default=1510868344.609079, null=True),
        ),
    ]
