# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_auto_20171116_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.IntegerField(blank=True, default=1510868562.3268535),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.FloatField(blank=True, default=1510868562.3248518, null=True),
        ),
    ]
