# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_auto_20171116_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.IntegerField(blank=True, default=1510868729.4087594),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.FloatField(blank=True, default=1510868729.4067569, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='categorysaver',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
