# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_auto_20171118_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.IntegerField(blank=True, default=1511045044.330812),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.FloatField(blank=True, default=1511045044.330812, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbsDownBy',
            field=models.CharField(blank=True, default='test', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbsUpBy',
            field=models.CharField(blank=True, default='test', max_length=10000, null=True),
        ),
    ]
