# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_auto_20171118_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='backedby',
            field=models.CharField(blank=True, default='test', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.IntegerField(blank=True, default=1511051452.9706945),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.FloatField(blank=True, default=1511051452.9706945, null=True),
        ),
    ]
