# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_auto_20171119_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='backedby',
            new_name='backedBy',
        ),
        migrations.AlterField(
            model_name='comment',
            name='added',
            field=models.IntegerField(blank=True, default=1511052541.3070195),
        ),
        migrations.AlterField(
            model_name='product',
            name='added',
            field=models.FloatField(blank=True, default=1511052541.3070195, null=True),
        ),
    ]
